const customNode = [{
    name: "流程",
    bkColor: "rgba(58, 109, 222, 0.6)",
    border: "2px solid #6192FF",
    borderRadius: "6px",
    width: "100px",
    fontColor: "#333",
    data: {
      name: "rectangle",
      text: "流程",
      rect: {
        width: 100,
        height: 40,
      },
      bkType: 0,
      fillStyle: "rgba(58, 109, 222, 0.6)",
      strokeStyle: "#6192FF",
      lineWidth: 2,
      borderRadius: 6,
      font: {
        color: "#333",
      },
      paddingLeft: 10,
      paddingRight: 10,
      paddingTop: 10,
      paddingBottom: 10,
      // hideInput: true,
      value: 3,
    },
  },
  {
    name: "判断",
    width: "104px",
    isImage: true,
    image: require('./images/diamond.png'),
    fontColor: "#333",
    data: {
      name: "diamond",
      text: "判断",
      rect: {
        width: 104,
        height: 40,
      },
      bkType: 0,
      fillStyle: "rgba(255, 188, 6, 0.5)",
      strokeStyle: "#FFBC06",
      lineWidth: 2,
      font: {
        color: "#333",
      },
      paddingLeft: 10,
      paddingRight: 10,
      paddingTop: 10,
      paddingBottom: 10,
      hideInput: true,
      value: 4,
    },
  },
  {
    name: "开始",
    bkColor: "rgba(0, 192, 59, 0.5)",
    border: "2px solid #00C03B",
    borderRadius: "6px",
    width: "100px",
    fontColor: "#333",
    data: {
      name: "rectangle",
      text: "开始",
      rect: {
        width: 100,
        height: 40,
      },
      bkType: 0,
      fillStyle: "rgba(0, 192, 59, 0.5)",
      strokeStyle: "#00C03B",
      lineWidth: 2,
      borderRadius: 6,
      font: {
        color: "#333",
      },
      paddingLeft: 10,
      paddingRight: 10,
      paddingTop: 10,
      paddingBottom: 10,
      // hideInput: true,
      value: 1,
    },
  },
  {
    name: "结束",
    bkColor: "rgba(255, 83, 83, 0.6)",
    border: "2px solid #FF5353",
    borderRadius: "6px",
    width: "100px",
    fontColor: "#333",
    data: {
      name: "rectangle",
      text: "结束",
      rect: {
        width: 100,
        height: 40,
      },
      bkType: 0,
      fillStyle: "rgba(255, 83, 83, 0.6)",
      strokeStyle: "#FF5353",
      lineWidth: 2,
      borderRadius: 6,
      font: {
        color: "#333",
      },
      paddingLeft: 10,
      paddingRight: 10,
      paddingTop: 10,
      paddingBottom: 10,
      // hideInput: true,
      value: 2,
    },
  },
  {
    name: "文本注释",
    bkColor: "#fff",
    border: "1px dashed #DDDDDD",
    borderRadius: "6px",
    width: "100px",
    fontColor: "#333",
    data: {
      name: "rectangle",
      text: "文本注释",
      rect: {
        width: 100,
        height: 40,
      },
      bkType: 0,
      fillStyle: "#fff",
      dash: 1,
      strokeStyle: "#DDDDDD",
      lineWidth: 1,
      borderRadius: 6,
      font: {
        color: "#333333",
      },
      paddingLeft: 10,
      paddingRight: 10,
      paddingTop: 10,
      paddingBottom: 10,
      // hideInput: true,
      value: 5,
    },
  }
];
export default customNode
